In [3]:
import numpy as np

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])
weights_input_hidden = np.random.rand(2, 2)
weights_hidden_output = np.random.rand(2, 1)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

hidden_layer = sigmoid(np.dot(x, weights_input_hidden))
output_layer = sigmoid(np.dot(hidden_layer, weights_hidden_output))
error = y - output_layer
d_predicted_output = error * sigmoid(output_layer)
error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
d_hidden_layer = error_hidden_layer * sigmoid(hidden_layer)
weights_hidden_output += hidden_layer.T.dot(d_predicted_output)
weights_input_hidden += x.T.dot(d_hidden_layer)

epochs = 10000
print("\nOutput Layer after {} epochs:".format(epochs))
print(output_layer)


Output Layer after 10000 epochs:
[[0.52512369]
 [0.52833382]
 [0.53364401]
 [0.53633077]]


In [7]:
print("Error :", error)

Error : [[-0.52512369]
 [ 0.47166618]
 [ 0.46635599]
 [-0.53633077]]


In [8]:
print("\nPredicted output: \n", d_predicted_output)
print("\nError hidden layer: \n", error_hidden_layer)
print("\nHidden_layer: \n",d_hidden_layer)


Predicted output: 
 [[-0.32995888]
 [ 0.29672256]
 [ 0.29395939]
 [-0.33840243]]

Error hidden layer: 
 [[-0.02521971 -0.04115446]
 [ 0.02267936  0.03700903]
 [ 0.02246816  0.03666439]
 [-0.02586507 -0.04220759]]

Hidden_layer: 
 [[-0.01569824 -0.02561698]
 [ 0.01417897  0.02386214]
 [ 0.01489628  0.02422024]
 [-0.01720675 -0.02863274]]
